### ISSUE TITLE
Whether to add a preview for floating win like fzf.vim?

### ISSUE THREAD

**Issue by jqhr** [mfussenegger/nvim-fzy#10]
Whether to add a preview for floating win like fzf.vim?

**Comment by mfussenegger** [comment]
the `fzy` cli itself doesn't provide a preview option so there is no easy way to implement a preview in nvim-fzy.

[telescope](https://github.com/nvim-telescope/telescope.nvim) can be configured to use the fzy algorithm - so I'd recommend to use that if you need more features than what nvim-fzy provides.

**Comment by jqhr** [comment]
ok
