### ISSUE TITLE
expose popup size in `pick_one()`

### ISSUE THREAD

**Issue by dchinmay2** [mfussenegger/nvim-fzy#14]
Title, for example it doesn't make sense to have a popup this wide when the choices are not as long

![image](https://user-images.githubusercontent.com/36493671/143292279-1fddc477-4d0f-4e94-b1cf-0a14003ce955.png)

**Comment by dchinmay2** [comment]
Because it takes a table, the user can pre-compute the longest choice in what they feed to `pick_one()`

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-fzy/issues/23 - I decided to just expose the full function to be overriden.

**Comment by dchinmay2** [comment]
awesome, thanks
