### ISSUE TITLE
Live grep example

### ISSUE THREAD

**Issue by hesseltuinhof** [mfussenegger/nvim-fzy#15]
Is there an easy way to configure a keybinding that allows for live grep across the working directory?

I am currently stuck with `fzy.execute('ag --nobreak --noheading .', fzy.sinks.edit_file)<cr>"`. This gives me something like this

![image](https://user-images.githubusercontent.com/10271772/144144679-f60f8c71-a6a3-4952-9a04-de63a2fa9be4.png)

Of course, `sinks.edit_file` can't open the selection and we need to further parse it. How best to proceed here? Any pointers are appreciated :heart:

**Comment by mfussenegger** [comment]
You could create a custom sink. Maybe something like this:


```lua
local M = {}

function M.edit_ag_selection(selection)
  if not selection then
    return
  end
  local parts = vim.split(selection, ':')
  local path = parts[1]
  vim.cmd('e ' .. path)
end
```

You'd put it somewhere in your `~/.config/nvim/lua/`, for example in `~/.config/nvim/lua/myfzy.lua` and then use

```
fzy.execute('ag --nobreak --noheading .', require('myfzy').edit_ag_selection)<cr>
```

**Comment by hesseltuinhof** [comment]
Works like a charm.

I just replaced

```lua
local path = parts[1]
vim.cmd('e ' .. path)
```

with 

```lua
local path, line = parts[1], parts[2]
vim.cmd("e +" .. line .. " " .. path)
```

Is such a live grep sink something you would consider adding? I can additionally test with `rg` and prepare a quick PR.

**Comment by mfussenegger** [comment]
Adding just the sink should be fine if the format works for other tools as well.
