### ISSUE TITLE
[Question] Resize window

### ISSUE THREAD

**Issue by idr4n** [mfussenegger/nvim-fzy#23]
Hi,
I wonder if it is possible to resize the fzy floating window, I just find it too big for my needs, and also ideally to be positioned at the bottom. Otherwise, I really like this plugin for its simplicity and snappiness.
Thanks!

**Comment by mfussenegger** [comment]
I merged a change to allow overriding the function that creates the floating window, so you can customize it:

```lua
require('fzy').new_popup = function()
  local buf = api.nvim_create_buf(false, true)
  api.nvim_buf_set_keymap(buf, 't', '<ESC>', '<C-\\><C-c>', {})
  api.nvim_buf_set_option(buf, 'bufhidden', 'wipe')
  local columns = api.nvim_get_option('columns')
  local lines = api.nvim_get_option('lines')
  local width = math.floor(columns * 0.9)
  local height = math.floor(lines * 0.8)
  local opts = {
    relative = 'editor',
    style = 'minimal',
    row = math.floor((lines - height) * 0.5),
    col = math.floor((columns - width) * 0.5),
    width = width,
    height = height,
    border = 'single',
  }
  local win = api.nvim_open_win(buf, true, opts)
  return win, buf
end
```


(This is the default implementation, you can adjust width/height or change the anchoring as needed. See `:h nvim_open_win`)

**Comment by idr4n** [comment]
That's awesome, thanks for this!
