### ISSUE TITLE
Is it possible to make the implementation of `vim.ui.select` optional?

### ISSUE THREAD

**Issue by JavaHello** [mfussenegger/nvim-fzy#43]
This way, I can use `fzy` to search for files without affecting `vim.ui.select`.

**Comment by mfussenegger** [comment]
Currently there's no option for that. But you could simply make sure that whatever you want to use for `vim.ui.select` overrides the function after nvim-fzy is loaded.

**Comment by JavaHello** [comment]
```lua
  {
    "nvim-telescope/telescope-ui-select.nvim",
    dependencies = {
      "mfussenegger/nvim-fzy",
    },
    event = "VeryLazy",
    config = function()
      require("telescope").load_extension "ui-select"
    end,
  },
````
thank you. It works fine after adding it as a dependency for `telescope-ui-select`.
