### ISSUE TITLE
how can i replace current buffer when finding files?

### ISSUE THREAD

**Issue by zzzeyez** [mfussenegger/nvim-fzy#5]
awesome plugin btw.  very speedy, just  wished it didn't create new buffers

**Comment by mfussenegger** [comment]
> awesome plugin btw. very speedy, just wished it didn't create new buffers

You could create your custom callback function.

Create a `~/.config/nvim/lua/util.lua` with:

```lua

local M = {}

function M.edit_file(filename)
  if filename and filename ~= '' then
    vim.cmd('bd! | e ' .. filename)
  end
end

return M
```

And then adapt your mapping:

```vimL
lua fzy = require('fzy')
nnoremap <silent><leader>ff :lua fzy.execute('fd', require('util').edit_file)<CR>
```


You can change the name of `util` / `util.lua` to anything else, but it shouldn't conflict with a plugin.

**Comment by zzzeyez** [comment]
awesome, that works perfectly.  thanks so much
