### ISSUE TITLE
Request: fzy native module

### ISSUE THREAD

**Issue by kkharji** [mfussenegger/nvim-fzy#6]
Hey @mfussenegger , awesome design I appreciate how simple and light weight it seems. I wonder if its possible to somehow add https://github.com/romgrk/fzy-lua-native as I think it would further enhance our experience.

Thanks

**Comment by mfussenegger** [comment]
It looks interesting, but I'm not sure how nvim-fzy would benefit from it. Currently nvim-fzy launches `fzy` to do the filtering, so matching and scoring should be fast enough.

Integrating fzy-lua-native could reduce the overhead of launching a process, but in turn I'd add a lot of complexity into this plugin which I'm currently not keen on maintaining, especially given that there is already [telescope](https://github.com/nvim-telescope/telescope.nvim) that went down that route. I don't intent do compete with that, but rather see nvim-fzy as complementing the ecosystem by providing a alternative with simpler design.
